### ISSUE TITLE
Compatibility with BepInEx

### ISSUE THREAD

**Issue by Xytronix** [Halbann/LazyOrbit#1]
Add compatibility for this modloader too

**Comment by linuxgurugamer** [comment]
That would be a separate mod, I've actually done that for myself, will see about releasing it soon

**Comment by linuxgurugamer** [comment]
@Halbann it's essentially a rebuild, using the BepinEx framework.  I can push it back to you here, if you like, or just release it as a clone for BepinEx.  let me know what you want to do

LGG

**Comment by Halbann** [comment]
I've not yet had a look at the BepInEx framework, do you think it's feasible to merge them into one mod that works with both loaders?

By the way, thanks so much for your work maintaining mods over the years!

**Comment by Halbann** [comment]
Hey @linuxgurugamer, I've just released a new version with rendezvous and landing, and I can't foresee there being any more changes save for bug fixes. Could I have a look at your BepInEx version to see if there's any possibility of merging them?

**Comment by linuxgurugamer** [comment]
Sure.
I forked the repo, merged in your latest changes, and committed it all in a new branch here:
https://github.com/linuxgurugamer/LazyOrbit/tree/LGG-BepInEx

I don't think you can have one dll for both, there were a couple of changes I had to make

**Comment by linuxgurugamer** [comment]
hey,  if you aren't going to support BepinEx, would you mind if I release a compatible version, derived from your mod?
Credit would be given, of course

**Comment by Halbann** [comment]
Going forward, I'm going to use SpaceWarp as an API for common KSP2-specific functions since it's now available as a BepInEx plugin. I think that's how most people are going to use it from now on. It makes sense to have a common KSP2-specific layer on top of a reliable mod loader.

Specifically, I wouldn't recommend releasing a BepinEx-only version because I'm going to move my toolbar code into SpaceWarp in the next update.

**Comment by linuxgurugamer** [comment]
ok
